-- Tabela de Usuários
CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Insumos
CREATE TABLE IF NOT EXISTS supplies
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku                VARCHAR(100) NOT NULL UNIQUE,
    name               VARCHAR(255) NOT NULL,
    description        VARCHAR(500) NOT NULL,
    unit_price         DECIMAL(15,2) NOT NULL,
    supplied_by        BIGINT,
    reserved_quantity  INT NOT NULL DEFAULT 0,
    available_quantity INT NOT NULL DEFAULT 0,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP NULL
);

-- Tabela de Serviços da Ordem de Serviço
CREATE TABLE IF NOT EXISTS services
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id   BIGINT NOT NULL,
    catalog_service_id BIGINT NOT NULL,
    price              DECIMAL(15, 2) NOT NULL,
    status             VARCHAR(50) NOT NULL,
    created_at         TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP NOT NULL,
    rejected_at        TIMESTAMP,
    cancelled_at       TIMESTAMP,
    approved_at        TIMESTAMP,
    started_at         TIMESTAMP,
    completed_at       TIMESTAMP
);

-- Tabela de Insumos Necessários por Serviço
CREATE TABLE IF NOT EXISTS service_needed_supplies
(
    service_id BIGINT NOT NULL,
    sku        VARCHAR(100),
    note       VARCHAR(500),
    quantity   INTEGER
);
