-- Tabela de Usuários
CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Clientes
CREATE TABLE IF NOT EXISTS owners
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255),
    document      VARCHAR(50),
    document_type VARCHAR(50),
    phone         VARCHAR(50),
    email         VARCHAR(255),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Veículos
CREATE TABLE IF NOT EXISTS vehicles
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id      BIGINT       NOT NULL,
    client_id     BIGINT       NOT NULL,
    license_plate VARCHAR(20)  NOT NULL UNIQUE,
    plate         VARCHAR(20)  NOT NULL UNIQUE,
    brand         VARCHAR(255) NOT NULL,
    model         VARCHAR(255) NOT NULL,
    vehicle_year  INTEGER      NOT NULL,
    vin           VARCHAR(100),
    color         VARCHAR(100) NOT NULL,
    fuel_type     VARCHAR(50)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vehicle_client FOREIGN KEY (client_id) REFERENCES owners (id)
);

-- Tabela de Ordens de Serviço
CREATE TABLE IF NOT EXISTS service_orders
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id             BIGINT      NOT NULL,
    vehicle_id            BIGINT      NOT NULL,
    description           VARCHAR(500),
    estimated_amount      DECIMAL(15, 2),
    status                VARCHAR(50) NOT NULL,
    created_at            TIMESTAMP   NOT NULL,
    updated_at            TIMESTAMP   NOT NULL,
    inspected_at          TIMESTAMP,
    partially_rejected_at TIMESTAMP,
    rejected_at           TIMESTAMP,
    cancelled_at          TIMESTAMP,
    approved_at           TIMESTAMP,
    started_at            TIMESTAMP,
    completed_at          TIMESTAMP,
    delivered_at          TIMESTAMP,
    CONSTRAINT fk_service_order_client FOREIGN KEY (client_id) REFERENCES owners (id),
    CONSTRAINT fk_service_order_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

-- Tabela de Insumos
CREATE TABLE IF NOT EXISTS supplies
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku                VARCHAR(100)   NOT NULL UNIQUE,
    name               VARCHAR(255)   NOT NULL,
    description        VARCHAR(500)   NOT NULL,
    unit_price         DECIMAL(15, 2) NOT NULL,
    supplied_by        BIGINT,
    reserved_quantity  INT            NOT NULL DEFAULT 0,
    available_quantity INT            NOT NULL DEFAULT 0,
    created_at         TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP      NULL
);

-- Tabela de Serviços Catalogados
CREATE TABLE IF NOT EXISTS catalog_services
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description TEXT,
    base_price  NUMERIC(10, 2),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NULL
);

-- Tabela de Serviços da Ordem de Serviço
CREATE TABLE IF NOT EXISTS services
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id   BIGINT         NOT NULL,
    catalog_service_id BIGINT         NOT NULL,
    price              DECIMAL(15, 2) NOT NULL,
    status             VARCHAR(50)    NOT NULL,
    created_at         TIMESTAMP      NOT NULL,
    updated_at         TIMESTAMP      NOT NULL,
    rejected_at        TIMESTAMP,
    cancelled_at       TIMESTAMP,
    approved_at        TIMESTAMP,
    started_at         TIMESTAMP,
    completed_at       TIMESTAMP
);

-- Tabela de Insumos Necessários por Serviço
CREATE TABLE IF NOT EXISTS service_needed_supplies
(
    service_id BIGINT NOT NULL,
    id_supply  INTEGER,
    note       VARCHAR(500),
    quantity   INTEGER
);
