-- Schema for local development with H2 in-memory database

CREATE TABLE IF NOT EXISTS owners
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    document      VARCHAR(255) NOT NULL UNIQUE,
    document_type VARCHAR(10)  NOT NULL,
    phone         VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS vehicles
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id      BIGINT       NOT NULL,
    license_plate VARCHAR(255) NOT NULL UNIQUE,
    brand         VARCHAR(255) NOT NULL,
    model         VARCHAR(255) NOT NULL,
    year          INTEGER      NOT NULL,
    color         VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL UNIQUE,
    password  VARCHAR(255) NOT NULL,
    role      ARRAY
);

CREATE TABLE IF NOT EXISTS supplies
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku                VARCHAR(100)   NOT NULL UNIQUE,
    name               VARCHAR(255)   NOT NULL,
    description        VARCHAR(500)   NOT NULL,
    unit_price         DECIMAL(15, 2) NOT NULL,
    supplied_by        BIGINT,
    reserved_quantity  INT            NOT NULL DEFAULT 0,
    available_quantity INT            NOT NULL DEFAULT 0,
    created_at         TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id   BIGINT         NOT NULL,
    catalog_service_id BIGINT         NOT NULL,
    price              DECIMAL(15, 2) NOT NULL,
    status             VARCHAR(50)    NOT NULL,
    created_at         TIMESTAMP      NOT NULL,
    updated_at         TIMESTAMP      NOT NULL,
    rejected_at        TIMESTAMP,
    cancelled_at       TIMESTAMP,
    approved_at        TIMESTAMP,
    started_at         TIMESTAMP,
    completed_at       TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_needed_supplies
(
    service_id BIGINT,
    id_supply  INTEGER,
    note       VARCHAR(500),
    quantity   INTEGER
);
