# application-ci.properties
spring.jpa.hibernate.ddl-auto=update

# Seed canônico
app.seed.enabled=true
app.seed.locations=classpath:db/seed/ci-seed.sql

# default
user.password.default=${DEFAULT_USER_PASSWORD:dummypassword}
