server.port=8080

# Expor o endpoint health
management.endpoints.web.exposure.include=health

# (Opcional) Mostrar detalhes completos da saúde (componentes)
management.endpoint.health.show-details=always


# DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/workshop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


#user
user.password.default=${DEFAULT_USER_PASSWORD}

#secret jwt - 32 caracteres ~
security.jwt.secret=${JWT_SECRET}

# chat bot api key
authentication.chatbot.api.key=${API_KEY_CHATBOT}