server.port=8080

# Expor o endpoint health
management.endpoints.web.exposure.include=health

# (Opcional) Mostrar detalhes completos da saúde (componentes)
management.endpoint.health.show-details=always


# DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/workshop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


#user
user.password.default=${DEFAULT_USER_PASSWORD}

#secret jwt - 32 caracteres ~
security.jwt.secret=${JWT_SECRET}

# chat bot api key
authentication.chatbot.api.key=${API_KEY_CHATBOT}

# Kafka
app.budget.kafka.enabled=${APP_BUDGET_KAFKA_ENABLED:false}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.admin.fail-fast=false
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:workshop-group}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
app.budget.kafka.topic.request=${APP_BUDGET_KAFKA_TOPIC_REQUEST:budget-approval-request}
app.budget.kafka.topic.decision=${APP_BUDGET_KAFKA_TOPIC_DECISION:budget-decision}

# Budget token TTL
app.budget.token.ttl-hours=${APP_BUDGET_TOKEN_TTL_HOURS:48}