apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: oficina-mecanica
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/workshop
  POSTGRES_DB: workshop
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:29092