apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-orcamentos
  namespace: oficina-mecanica

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ms-orcamentos

  template:
    metadata:
      labels:
        app: ms-orcamentos

    spec:
      containers:
        - name: ms-orcamentos

          image: leonardooziro/ms-orcamentos:latest
          
          ports:
            - containerPort: 8081

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS

            - name: SPRING_MAIL_HOST
              value: mailpit-service

            - name: SPRING_MAIL_PORT
              value: "1025"

            - name: APP_BUDGET_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_BUDGET_BASE_URL
