apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: oficina-mecanica
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  API_KEY_CHATBOT: "${API_KEY_CHATBOT}"
  SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  DEFAULT_USER_PASSWORD: "${DEFAULT_USER_PASSWORD}"
  SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
  POSTGRES_USER: "${POSTGRES_USER}"