apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: oficina-mecanica
type: Opaque
stringData:
  #trocar essas variaveis depois para utilizar as do github
  JWT_SECRET: "cde8e1df5a010e6d05324cfa710becd6"
  API_KEY_CHATBOT: "teste"
  SPRING_DATASOURCE_PASSWORD: "admin"
  POSTGRES_PASSWORD: "admin"
  DEFAULT_USER_PASSWORD: "123"
  SPRING_DATASOURCE_USERNAME: "admin"
  POSTGRES_USER: "admin"