version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: workshop-db
    environment:
      POSTGRES_DB: workshop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example -d workshop"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
