env:
  contexts:
    - name: "app-context"
      urls:
        - "http://${APP_IP}:8080"
      includePaths:
        - "http://${APP_IP}:8080/.*"
      authentication:
        method: "manual"
      sessionManagement:
        method: "headers"
      users:
        - name: "admin"
          credentials:
            Authorization: "Bearer ${ZAP_TOKEN_ADMIN}"

jobs:
  - type: openapi
    parameters:
      apiFile: http://${APP_IP}:8080/v3/api-docs
      targetUrl: http://${APP_IP}:8080

  - type: spider
    parameters:
      context: "app-context"
      user: "admin"

  - type: activeScan
    parameters:
      context: "app-context"
      user: "admin"

  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "/zap/wrk"
      reportFile: "zap-report.html"