name: Deploy Application

on:

  workflow_dispatch:

    inputs:

      application:

        description: "Deseja fazer deploy de qual aplicação?"

        required: true

        type: choice

        options:
          - Monolito
          - Ms - Orcamentos


jobs:

  build-app:
    
    name: Build Application

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Define Maven Path Variable 🔎
        run: |
          if [ "${{ github.event.inputs.application }}" = "Monolito" ]; then
            echo "MAVEN_WORKDIR=." >> $GITHUB_ENV
          else
            echo "MAVEN_WORKDIR=./ms-orcamentos" >> $GITHUB_ENV
          fi

      - name: Build and Tests App ☕
        working-directory: ${{ env.MAVEN_WORKDIR }}
        run: mvn clean install

        


  deploy-app:

    name: Deploy Application

    needs: build-app

    runs-on: maquina-leo

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Define Deployment Variables 🔎

        run: |

          if ("${{ github.event.inputs.application }}" -eq "Monolito") {

            echo "IMAGE_NAME=sistema-oficina-mecanica-mnl" >> $env:GITHUB_ENV
            echo "DEPLOYMENT_MANIFEST=./k8s/deployment-monolito.yaml" >> $env:GITHUB_ENV

            echo "DOCKERFILE=./Dockerfile" >> $env:GITHUB_ENV
            echo "BUILD_CONTEXT=." >> $env:GITHUB_ENV

            echo "MAVEN_WORKDIR=." >> $env:GITHUB_ENV

          }
          else {

            echo "IMAGE_NAME=ms-orcamentos" >> $env:GITHUB_ENV
            echo "DEPLOYMENT_MANIFEST=./k8s/deployment-ms-orcamentos.yaml" >> $env:GITHUB_ENV

            echo "DOCKERFILE=./ms-orcamentos/Dockerfile" >> $env:GITHUB_ENV
            echo "BUILD_CONTEXT=./ms-orcamentos" >> $env:GITHUB_ENV

            echo "MAVEN_WORKDIR=./ms-orcamentos" >> $env:GITHUB_ENV

          }

          echo "IMAGE_SHA=${{ github.sha }}" >> $env:GITHUB_ENV
      
      - name: Restore Terraform State 🔁
        run: |
          ./scripts/restore-terraform-state.ps1
      
      - name: Debug Variables
        run: |
          Write-Host "Registry: ${{ vars.DOCKER_REGISTRY }}"
          Write-Host "Image: ${env:IMAGE_NAME}"
          Write-Host "SHA: ${env:IMAGE_SHA}"
          Write-Host "Dockerfile: ${env:DOCKERFILE}"
          Write-Host "Context: ${env:BUILD_CONTEXT}"

      - name: Build Docker Image 🐋
        run: |
          docker build `
            -f ${env:DOCKERFILE} `
            -t ${{ vars.DOCKER_REGISTRY }}/"${env:IMAGE_NAME}":latest `
            -t ${{ vars.DOCKER_REGISTRY }}/"${env:IMAGE_NAME}":"${env:IMAGE_SHA}" `
            ${env:BUILD_CONTEXT}
      
      - name: Push New Version to Registry 🐋
        run: |
          docker push ${{ vars.DOCKER_REGISTRY }}/"${env:IMAGE_NAME}":latest
          docker push ${{ vars.DOCKER_REGISTRY }}/"${env:IMAGE_NAME}":"${env:IMAGE_SHA}"
      
      - name: Run terraform init
        working-directory: infra
        run: terraform init
      
      - name: Update Deployment Manifest 📝

        run: |

          ./scripts/replace-image-tag.ps1 `
            -Manifest "${env:DEPLOYMENT_MANIFEST}" `
            -Registry "${{ vars.DOCKER_REGISTRY }}" `
            -Image "${env:IMAGE_NAME}" `
            -Tag "${env:IMAGE_SHA}"
      
      - name: Deploy Application 🚀

        working-directory: infra

        run: terraform apply -auto-approve
      
      - name: Backup Terraform State
        run: |
          ./scripts/backup-terraform-state.ps1
      
      - name: Log Success ✅
        run: echo "Deploy de ${env:IMAGE_NAME} Concluído!"