name: Destroy Infra | Terraform

on:
  workflow_dispatch:

jobs:
  destroy-infra:
    name: Destroy Local Cluster and Resources
    runs-on: maquina-leo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Destroy Resources with Terraform
        run: terraform destroy -auto-approve
        working-directory: infra
      