name: Destroy Infra | Terraform

on:
  workflow_dispatch:

jobs:
  destroy-infra:
    name: Destroy Local Cluster and Resources
    runs-on: maquina-leo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore tf state  🔁 
        run: |
          ./scripts/restore-terraform-state.ps1
      
      - name: Run terraform init
        run: terraform init
        working-directory: infra

      - name: Destroy Resources with Terraform  ☠️
        run: terraform destroy -auto-approve
        working-directory: infra
      
      - name: Backup Terraform State  🔁 
        run: |
          ./scripts/backup-terraform-state.ps1
      
      - name: Log Success ✅
        run: echo "Infra desprovisionada! Destroy bem sucedido."