name: Set up Infra | Terraform

on:
  workflow_dispatch:

jobs:
  setup-infra:
    name: Set up Local Cluster
    runs-on: maquina-leo

    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4
      
      - name: Set Up Terraform
        run: terraform init
        working-directory: infra
      
      - name: Validate Terraform Code
        run: terraform validate
        working-directory: infra
      
      - name: Plan Terraform Resources
        run: terraform plan
        working-directory: infra
      
      - name: Create Minikube Cluster
        run: terraform apply -target=null_resource.minikube -auto-approve
        working-directory: infra

      
      - name: Create Namespaces and Install dependencies with HELM
        run: terraform apply -auto-approve
        working-directory: infra
      
      - name: Log Success
        run: echo "Cluster criado!! Namespaces, metrics server e ingress configurados! ☸️🐋"
